# Service to register sensors in the fusion layer
# sensors not registered will have its data ignored in fusion
string name

# All relative to the vehicle coordinate frame
float32 x
float32 y
float32 angle

# Which attributes from object_model_msgs/msg/Track.state this sensor is able to provide
# Size is object_model_msgs::msg::Track::STATE_SIZE
bool[8] capable  

# The R matrix from EKF
# 6x6 matrix, according to CTRA model
# Ros/columns are about attributes [x, y, v, a, yaw, yaw_rate], order matters
float32[36] measurement_noise_matrix
---
# Success/error message
string status
