# Should be built having the repository root as context
FROM ros:foxy-ros-base

RUN mkdir -p /ros2_ws/src

# To be independent from binding volumes
COPY . /ros2_ws/src

WORKDIR /ros2_ws

# Core dependencies
RUN rosdep install -i --from-path src --rosdistro foxy -y \
  && . /opt/ros/foxy/setup.sh \
  && colcon build --event-handlers console_cohesion+ \
  && ln -s /ros2_ws/src/docker/entrypoint.sh /entrypoint.sh

# To keep a backup in case of binding
RUN cp -aT /ros2_ws/build /opt/build \
  && cp -aT /ros2_ws/install /opt/install \
  && cp -aT /ros2_ws/log /opt/log

ENV FASTRTPS_DEFAULT_PROFILES_FILE="/ros2_ws/src/docker/fastrtps-profile.xml"

ENTRYPOINT ["/entrypoint.sh"]

CMD /opt/ros/foxy/bin/ros2 run fusion_layer fusion > fusion_layer.csv
